### ISSUE TITLE
XT1955: Broken audio

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/motorola-kernel-modules#4] opened 2020-04-22 20:14 UTC
On Ocean , We are forced to use MONO audio to hear both Left and Right speaker channels... Otherwise we only hear Left channel.. Issue does not exist in stock
Can Motorola please provide fix for this ?

**Comment by awheeler-mmi** [comment] 2020-04-22 21:18
Hey @wh0dat,

If you get a log then I could route it to the audio team.  But if it's not a stock ROM then I'd definitely recommend working with other developers over at XDA.

-andrew

**Comment by bernie-nix** [comment] 2020-04-22 22:25
Hi @awheeler-mmi,

I can confirm the issue mentioned by @wh0dat exists on all roms built from source for the G7 Power. I am from XDA and a moderator in a telegram group of over 350 G7 users and rom developers, and we have been scratching our heads on this one. I have attached a log duplicating the sound issue by:

1. Selecting Youtube video "left right audio test" https://www.youtube.com/watch?v=6TWJaFD6R2s&t=10s
2. Playing the video results in audio only audible on the left channel when listening on speaker. Headphones, bluetooth, etc. all work in stereo
3. This error is not present when building from source using on the G7 Play and River
4. I believe this error reflects the following error in the log: "04-22 17:13:55.016 E/msm8916_platform(631): platform_check_backends_match: Invalid snd_device ="
AND/OR
Source mixer paths don't work with the open source audio hal....
5. Please see attached log.
[2020-04-22-17-15-53.txt](https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/files/4519277/2020-04-22-17-15-53.txt)


Please let me know if there are any other files, logs or information we can provide to the audio team. We really appreciate your help here. Best wishes and stay safe!

**Comment by awheeler-mmi** [comment] 2020-04-23 02:19
Hmm.. off the cuff, I am curious why the HAL is using the 8916 audio platform driver, and not the 8974 platform driver.  It should be using the 8974 platform driver.

**Comment by bernie-nix** [comment] 2020-04-24 03:04
@awheeler-mmi Thank you for your reply. I'm going to take your comment back to a few devs and look into it this weekend. Really appreciate your time!

**Comment by vinimed** [comment] 2021-10-26 15:38
Hello @bernie-nix, due to the long time without updates, we are closing the issue. If you are still facing errors, please re-open the issue. Thank you in advance.

**Closed as completed by vinimed** 2021-10-26 15:38 UTC
